version: '3.8'

services:
  database:
    image: postgres:17
    container_name: portfolio-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio-network

  api:
    build:
      context: ./apps/api/
      dockerfile: Dockerfile
    container_name: portfolio-api
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: portfolio-db
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - '3001:3001'
    depends_on:
      - database
    networks:
      - portfolio-network
    volumes:
      - ./apps/api:/app:delegated
      - /app/node_modules

volumes:
  postgres_data:

networks:
  portfolio-network:
    driver: bridge
